######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 17 16:22:18 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=phonon
# Input
HEADERS += helpui.h mainwindow.h mediafile.h ui_mainwindow.h ui_helpdialog.h
FORMS += helpdialog.ui mainwindow.ui
SOURCES += helpdialog.cpp main.cpp mainwindow.cpp mediafile.cpp
